// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYNppivvB_sCrQJ6FAAvrdnDCC-JadAs',
    appId: '1:632713114625:web:c73c6d153877747cf6bc00',
    messagingSenderId: '632713114625',
    projectId: 'yandex-musics',
    authDomain: 'yandex-musics.firebaseapp.com',
    storageBucket: 'yandex-musics.appspot.com',
    measurementId: 'G-M3TJ7GQ9JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2mDG2uZc-2s8Y9cRqhGxEJUhdXaxFhg',
    appId: '1:632713114625:android:9ab1860b413da3e8f6bc00',
    messagingSenderId: '632713114625',
    projectId: 'yandex-musics',
    storageBucket: 'yandex-musics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9J0W6vnK1yQX1yD-PgCg8KFZEkHrjSA8',
    appId: '1:632713114625:ios:aa126cd09633d7b6f6bc00',
    messagingSenderId: '632713114625',
    projectId: 'yandex-musics',
    storageBucket: 'yandex-musics.appspot.com',
    iosBundleId: 'com.example.playerMusicProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYNppivvB_sCrQJ6FAAvrdnDCC-JadAs',
    appId: '1:632713114625:web:f662c32eccc2ca12f6bc00',
    messagingSenderId: '632713114625',
    projectId: 'yandex-musics',
    authDomain: 'yandex-musics.firebaseapp.com',
    storageBucket: 'yandex-musics.appspot.com',
    measurementId: 'G-V5X9VM6H4D',
  );
}
